FROM tensorflow/tensorflow:2.4.1
# ADD .. /developer
# LABEL maintainer="s-diaco"

# [Optional] Uncomment this section to install additional OS packages.
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends \
    git

RUN pip install torch==1.8.0+cpu torchvision==0.9.0+cpu \ 
    torchaudio==0.8.0 -f https://download.pytorch.org/whl/torch_stable.html

# [Optional] If your pip requirements rarely change, uncomment this section to add them to the image.
COPY requirements.txt /tmp/pip-tmp/
RUN pip3 --disable-pip-version-check --no-cache-dir install -r /tmp/pip-tmp/requirements.txt \
    && rm -rf /tmp/pip-tmp
# RUN pip3 --disable-pip-version-check --no-cache-dir install git+git://github.com/quantopian/pyfolio.git
# RUN pip3 --disable-pip-version-check --no-cache-dir install git+git://github.com/Glyphack/pytse-client.git
